import React from 'react'
import Image from 'next/image'

const Abouthis = () => {
  return (
    <div className="bg-white py-24 sm:py-32">
  <div className="mx-auto px-6 lg:px-8">
    <div className="mx-auto lg:mx-0">
      <h2 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">The Golf Club of Lebanon is a club with a history and more than a few tales to tell.</h2>
      <p className="mt-2 text-lg leading-8 text-gray-600">The American Consul and a group of Lebanese notables founded the Club and registered it under the name “The Sporting Club of Beirut (Golf)”. Located originally in Bir Hassan, on the old airport road, it started with a 1,500 square meters of land on top of a hill, overlooking sand dunes and amidst a forest of pine trees planted by Ibrahim Pasha during the first half of the 19th century to protect Beirut from the ravages of sand storms.</p>
    </div>
    <div className='flex flex-col py-10 items-center sm:py-18 gap-4 lg:flex-row'>
        <p>At that time, the club had some 200 members, most of them non-Lebanese, and the committee engaged the services of an Egyptian pro, Ibrahim Youssef Ibrahim, known as Baba Ibrahim by everyone, to give golf lessons. With the expansion of Beirut, owners of the dunes of Bir Hassan progressively reclaimed their properties until the club shrank down to a small area of land surrounding the club house, a structure with a kitchen and two changing rooms. It became abundantly clear that the club needed find a new home. In the late fifties, a new member joined the club; Salim Salaam, who was then at MEA and later, became Chairman. He came to learn that the Civil Aviation Authority owned some 200,000 square meters of sand dunes upon which steel aerials for the communications of the Airport had been erected. He struck a deal with the Aviation Authority and the Club was granted a fifteen-year Agreement from the Lebanese Government to plant the sand dunes with grass, thus protecting the installations of the Communications Center, which used to suffer great damage from the sand storms. This agreement has since been renewed to this day. In 1963, a British golf architect was brought over from England to design a nine-hole golf course with alternative tees and greens, and the first golf game on this new course was played in October 1965.From 1975 to 1990, much of Beirut was ravaged by civil war, and the Golf Club suffered a great deal.</p>
        <Image className='h-full w-full lg:w-1/3' src="/membership.jpg" width={500} height={100} alt='membership'/>   
    </div>
    <div className='flex flex-col gap-4 items-center lg:flex-row'>
        <p>In 1982, Israel invaded Lebanon, and the club's trees, grass and buildings were destroyed by tanks. Just after the Israeli withdrawal, the reconstruction started immediately and intensively. The Club reopened soon after, and the golf course became operational once more; the swimming pool was renovated, a squash court was re-constructed, the six tennis courts were repaired and improved all out of funds generated by its members. The Club has a full calendar of tournaments and events in each and every field of activity. This includes monthly medals and sponsored competitions and championships. Salim Salaam is given credit for having founded the Arab Golf Federation in 1975 and initiated the Arab Golf Championship from the GCL which hosted the 1st Arab Championship that year and is played annually in different Arab countries ever since. The Club went on to host many major regional golf tournaments. The Club’s players have been collecting medals and championships from different tournaments around the Middle East and the Mediterranean Basin.  It goes without saying that the Golf Club of Lebanon is always very proud of its champions.</p>
        <Image className='h-full w-full lg:w-1/3' src="/golfguy.jpg" width={500} height={100} alt='golfguy'/> 
    </div> 
    <div className="mx-auto flex flex-col lg:mx-0">
      <h2 className="text-2xl font-bold tracking-tight text-gray-900 pt-8 sm:text-3xl">President history.</h2>
      <Image className='h-full w-full justify-center p-4 lg:w-3/4' src="/presidents.png" width={500} height={100} alt='president'/>
    </div>
    </div>
    </div>
  )
}

export default Abouthis